# Thay YOUR_SONARCLOUD_ORG_KEY và YOUR_SONARCLOUD_PROJECT_KEY sau khi tạo project trên https://sonarcloud.io
sonar.organization=chuong-dev17
sonar.projectKey=chuong-dev17_do-an-bao-mat-ci
sonar.host.url=https://sonarcloud.io

sonar.sources=Car_Dealership/src
sonar.exclusions=**/.github/**,**/node_modules/**
